#!/bin/sh
set -eu

echo "pre-commit: gofmt"
test -z "$(gofmt -l .)"

echo "pre-commit: go vet"
go vet ./...

echo "pre-commit: go test"
go test ./...

echo "pre-commit: golangci-lint"
go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2 run

echo "pre-commit: npm check"
npm run check
